services:
    revinate_search.elasticsearch_service:
        class: Revinate\SearchBundle\Service\ElasticaService
        arguments: ['@service_container']
    revinate_search:
        class: Revinate\SearchBundle\Service\RevinateSearch
        arguments:
            - "%revinate_search.config.connections%"
            - "%revinate_search.config.paths%"
            - "@kernel"
    revinate_search.search_manager:
        class: Revinate\SearchBundle\Lib\Search\SearchManager
        arguments:
            - "@revinate_search.internal.configuration"
            - "@revinate_search.internal.client"
            - "@revinate_search.internal.event_manager"
    revinate_search.mapping_manager:
        class: Revinate\SearchBundle\Lib\Search\ElasticSearch\MappingManager
        arguments:
            - "@revinate_search.search_manager"
            - "%revinate_search.config.env%"

    # Private services
    revinate_search.internal.elasticsearch_callback_serializer:
        class: Revinate\SearchBundle\Lib\Search\Serializer\CallbackSerializer
        arguments:
            - toESDocument
            - fromESDocument
        public: false
    revinate_search.internal.cache_provider:
        class: Doctrine\Common\Cache\ArrayCache
        public: false
    revinate_search.internal.event_manager:
        class: Doctrine\Common\EventManager
        public: false
    revinate_search.abstract.configuration:
        class: Revinate\SearchBundle\Lib\Search\Configuration
        public: false
    revinate_search.abstract.client:
        class: Revinate\SearchBundle\Lib\Search\ElasticSearch\Client
        public: false
